@startuml

title Coffee Shop Model

namespace shared_kernel {

  class Amount {
    +quanity: BigDecimal
  }
  Amount .. "1" MeasurementUnit: uses

  enum MeasurementUnit {
    PIECES
    KILOGRAMS
    POUNDS
    LITRES
    FLUID_OUNCE
  }

  class CurrencyValue {
    +quanity: BigDecimal
  }
  CurrencyValue .. "1" Currency: uses

  enum Currency {
    US_DOLLAR
    MEXICAN_PESO
    BITCOIN
  }

    class OrderSubmitted <<event>> {
    +orderId: integer
    +calculatePrice: CurrencyValue
  }

}

namespace ordering {

  class Order {
    +id: integer
    void addOrderItem(menuItem: MenuItem, quantity: integer, specialInstructions: String)
    void removeOrderItem(OrderItem orderItem)
    void submitForPayment()
    void cancel()
    CurrencyValue calculatePrice()
  }
  Order *-- "0..*" OrderItem
  Order o-- "0..1" Customer
  Order o-- "0..*" Promotions
  Order .. "1" OrderStatus: uses

  enum OrderStatus {
    RECEIVING
    SUBMITTED
  }

  class Customer {
    +id: integer
  }

  class OrderItem {
    +id: integer
    +specialInstructions: String
    +quantity: integer
  }
  OrderItem o-- "1" MenuItem
  OrderItem *-- "1" shared_kernel.Amount

  MenuItem *-- "1..*" FoodBeverage
  MenuItem *-- "1..*" PricingOffer

    class FoodBeverage {
    +name: String
    +description: String
  }

  class PricingOffer {
    +name: String
  }
  PricingOffer *-- "1" shared_kernel.Amount
  PricingOffer *-- "1" shared_kernel.CurrencyValue

}

namespace payment {

  note "TODO payment processing" as n1

}

namespace kitchen {

  note "TODO food and beverage order preparation" as n1

}

namespace supplier {

  note "TODO supplier" as n1

}

namespace management {

  note "TODO management" as n1

}

@enduml
