@startuml

title Coffee Shop Model

namespace shared_kernel {

  enum UbiquitousLanguage #White {
    Size: a physical amount of something in MeasurementUnits
    CurrencyValue: some amount of a given currency
  }

  class Size {
    +quanity: BigDecimal
  }
  Size .. "1" MeasurementUnit: uses

  enum MeasurementUnit {
    PIECES
    KILOGRAMS
    POUNDS
    LITRES
    FLUID_OUNCE
  }

  class CurrencyValue {
    +quanity: BigDecimal
  }
  CurrencyValue .. "1" Currency: uses

  enum Currency {
    US_DOLLAR
    MEXICAN_PESO
    BITCOIN
  }

  class OrderPlaced <<event>> {
    +locationId: integer
    +orderId: integer
    +currencyValue: CurrencyValue
    +items: ordering.MenuItem[]
    +dateTime: ZonedDateTime
  }

  class OrderPaid <<event>> {
    +locationId: integer
    +orderId: integer
    +dateTime: ZonedDateTime
  }

  class OrderReadyForCustomer <<event>> {
    +kitchenOrderId: integer
    +locationId: integer
    +orderId: integer
    +dateTime: ZonedDateTime
  }

}

namespace ordering {

  enum UbiquitousLanguage #White {
    Location: the physical restaurant where an order may be placed
    Menu: A list of menu items that may change over time
    Order: A list of order items for a customer, may change before the order is placed
    FoodBeverage: Something that a customer might order from a coffee shop, e.g. coffee
    PricingOffer: The price for which a given quantity of FoodBeverage may be purchased
  }

  class Location {
    +id: integer
    +name: String

    Menu createMenu()
    void deleteMenu(Menu)

    Order createOrder()
  }

  note left of Location::submitForPayment
    emits shared_kernel.OrderPlaced
  end note

  Location *-- "0..*" Menu
  Location *-- "0..*" Order
  Location o-- "1..*" kitchen.Kitchen
  

  class Menu {
    +id: integer
    void addMenuItem(toMenu: Menu, foodBeverages: FoodBeverage[], pricingOffers: PricingOffer[])
    void removeMenuItem(fromMenu: Menu, menuItem: MenuItem)
  }
  Menu o-- "0..*" MenuItem

  class Order {
    +id: integer
    +customerName: String
    void addOrderItem(toOrder: Order, menuItem: MenuItem, quantity: integer, specialInstructions: String)
    void removeOrderItem(fromOrder: Order, orderItem: OrderItem)
    CurrencyValue calculatePrice(order: Order)
    void submitForPayment(order: Order)
    void cancelOrder(order: Order)
  }
  Order *-- "0..*" OrderItem
  Order *-- "1" OrderStatus

  enum OrderStatus {
    RECEIVING
    SUBMITTED
    CANCELLED
  }

  class OrderItem {
    +id: integer
    +specialInstructions: String
    +quantity: integer
    +size: shared_kernel.Size
  }
  OrderItem o-- "1" MenuItem

  MenuItem *-- "1..*" FoodBeverage
  MenuItem *-- "1..*" PricingOffer

  class FoodBeverage {
    +name: String
    +description: String
  }
  FoodBeverage o-- "1" kitchen.Recipe

  class PricingOffer {
    +name: String
    +size: shared_kernel.Size
    +currencyValue: shared_kernel.CurrencyValue
  }

}

namespace kitchen {

  enum UbiquitousLanguage #White {
    Kitchen: the physical location where an order may be prepared for the customer
    Order: A list of order items for a customer
    Recipe: the instructions for preparing an OrderItem
  }

  class Kitchen {
    id: integer
  }
  Kitchen *-- "0..*" Order

  note left of Kitchen
    emits shared_kernel.OrderReadyForCustomer
  end note

  note bottom of Kitchen
    creates Order on sharedKernel.OrderPlaced
  end note

  class Order {
    +id: integer
  }
  Order o-- "1" ordering.Order
  Order *-- "0..*" OrderItem

  class OrderItem {
    +quantity: integer
    +size: shared_kernel.Size
    void setReady()
  }
  OrderItem o-- "1" Recipe
  OrderItem o-- "1" KitchenStatus

  enum KitchenStatus {
    PENDING
    PREPARING
    READY
  }

  class Recipe {
    +id: integer
  }

}

namespace payment #LightGrey {
  note "generic subdomain" as n1 #LightGrey
}

namespace inventory #LightGrey {
  note "generic subdomain" as n1 #LightGrey
}

namespace suppliers #LightGrey {
  note "generic subdomain" as n1 #LightGrey
}

namespace workforce_management #LightGrey {
  note "generic subdomain" as n1 #LightGrey
}

namespace accounting #LightGrey {
  note "generic subdomain" as n1 #LightGrey
}

namespace marketing #LightGrey {
  note "generic subdomain" as n1 #LightGrey
}

@enduml
